
version: '3.3'
services:
    apache2-php-ssl:
        volumes:
            - '${DOCUMENT_ROOT}:/var/www/'
            - '${SITES_ENABLED}:/etc/apache2/sites-enabled'
            - '${SSL_ROOT}:/etc/apache2/ssl-cert'
        ports:
            - '80:80'
            - '443:443'
        environment:
            - 'DOMAINS=${DOMAINS}'
            - 'WEBMASTER_MAIL=${WEBMASTER_MAIL}'
        container_name: php-ssl
        image: 'pxlart/apache-php-ssl:1.0'
